const tileProperties = {
    'base': {
        model: './dungeon-tile-base.glb',
        description: 'Base tile that is unflipped',
        role: 'Movement',
        type: 'Base',
        neighbors: null,
        probability: 0.1,
    },
    'start': {
        model: './tile-start.glb',
        description: 'Tile that player starts on',
        role: 'Game State',
        type: 'Start',
        neighbors: null,
        probability: 0.1,
    },
    'end': {
        model: './tile-end.glb',
        description: 'Tile with end game condition',
        role: 'Game State',
        type: 'End',
        neighbors: [0, 0, 0, 1],
        probability: 0.1,
    },
    'cornerLeft': {
        model: './tile-corner-l.glb',
        description: 'Tile that lets player go to left',
        role: 'Movement',
        type: 'Corner',
        neighbors: [0, 0, 1, 1],
        probability: 0.1,
    },
    'cornerRight': {
        model: './tile-corner-r.glb',
        description: 'Tile that lets player go to right',
        role: 'Movement',
        type: 'Corner',
        neighbors: [1, 0, 0, 1],
        probability: 0.1,
    },
    'cornerLeftBrick': {
        model: './tile-corner-l-brick.glb',
        description: 'Tile that lets player go to left, but with immured alcove',
        role: 'Dialog',
        type: 'Corner',
        neighbors: [0, 0, 1, 1],
        probability: 0.1,
    },
    'cornerRightBrick': {
        model: './tile-corner-r-brick.glb',
        description: 'Tile that lets player go to right, but with immured alcove',
        role: 'Dialog',
        type: 'Corner',
        neighbors: [1, 0, 0, 1],
        probability: 0.1,
    },
    'wallLeft': {
        model: './tile-wall-left.glb',
        description: 'Tile with wall on left that lets player go forward or right',
        role: 'Movement',
        type: 'Wall',
        neighbors: [1, 1, 0, 1],
        probability: 0.1,
    },
    'wallForward': {
        model: './tile-wall-forward.glb',
        description: 'Tile with wall in front that lets player go left or right',
        role: 'Movement',
        type: 'Wall',
        neighbors: [1, 0, 1, 1],
        probability: 0.1,
    },
    'wallRight': {
        model: './tile-wall-right.glb',
        description: 'Tile with wall on right that lets player go forward or left',
        role: 'Movement',
        type: 'Wall',
        neighbors: [0, 1, 1, 1],
        probability: 0.1,
    },
    'hall': {
        model: './tile-hall.glb',
        description: 'Hallway tile for movement',
        role: 'Movement',
        type: 'Hallway',
        neighbors: [0, 1, 0, 1],
        probability: 0.1,
    },
    'deadEnd': {
        model: './tile-deadend.glb',
        description: 'Dead end tile',
        role: 'Movement',
        type: 'Dead End',
        neighbors: [0, 0, 0, 1],
        probability: 0.1,
    },
    'deadEndBook': {
        model: './tile-deadend-book.glb',
        description: 'Dead end tile that has book clue',
        role: 'Clue',
        type: 'Dead End',
        neighbors: [0, 0, 0, 1],
        probability: 0.1,
    },
    'bottle': {
        model: './tile-bottle.glb',
        description: 'Pillar tile that has health refill',
        role: 'Health',
        type: 'Pillar',
        neighbors: [1, 1, 1, 1],
        probability: 0.1,
    },
    'barrel': {
        model: './tile-barrel.glb',
        description: 'Dead end tile that has health refill',
        role: 'Health',
        type: 'Dead End',
        neighbors: [0, 0, 0, 1],
        probability: 0.1,
    },
}